### ISSUE TITLE
Check for gnuisms

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#57]
Make sure we're not relying on GNU only bits (sed options?)

**Comment by gdevenyi** [comment]
sed looks okay, bsd and gnu sed both support "-n"

**Comment by josephdviviano** [comment]
Your use of sed is causing trouble for us:

    sed: -e expression #1, char 5: invalid usage of line address 0

is all I get back when I run this command:

    qbatch --logdir ./ -N qap-test --walltime 1:00:00 qap-cmds

I can make the error go away by using `-b local`

**Comment by pipitone** [comment]
Thanks for the report. Okay, let's try to reproduce this. Can you send us the script that's being , e.g. `.qbatch/qap-test.array`. Depending on the version of qbatch you're using (can you tell us that also), you may find that file in the folder `.scripts/`. Also, what python version and OS are you running this with?

**Comment by pipitone** [comment]
@gdevenyi, from poking around sed a bit, I can get the same error if I run `sed -n 0,+1p file.txt`. sed doesn't like a 0 as the first address (under most circumstances). We should never have a 0 in the first address, because `$(( (${ARRAY_IND} - 1) * ${CHUNK_SIZE} + 1 ))` > 0 if `ARRAY_IND` and `CHUNK_SIZE` are > 0. which they must be... unless perhaps `ARRAY_IND` isn't being set properly and returning blank (i.e. old code with bug #62?).

Side note: which reminds me, maybe we should `set -u` in the scripts to fail on unset variable expansions, but we'll have to chat a bit more about how to implement #56 if this isn't supported in all shells.

**Comment by gdevenyi** [comment]
@josephdviviano can we get a copy of the script that qbatch generates? (either in ``.scripts/qat-test.array`` or ``.qbatch/qap-test.array``)

**Comment by josephdviviano** [comment]
Sure, see attached `.zip`.

I'm wondering if this line `ARRAY_IND=$PBS_ARRAYID` is the problem, as we're not running PBS. I'm guessing I just need to specify SGE in my call to `qbatch`.

If this is true it might be good for the program to check that you have the correct queue system running, and error out if not, instead of throwing this error.

[qap-test.array.zip](https://github.com/pipitone/qbatch/files/467593/qap-test.array.zip)

**Comment by josephdviviano** [comment]
@pipitone I believe this might be related to #62 but this is a very recent pull of the code (last few days), so it must be slightly different.

**Comment by gdevenyi** [comment]
@josephdviviano did this job get properly run as an array job?

Did you get an error for all 1612 slices?

**Comment by gdevenyi** [comment]
@pipitone I see two possible problems that could cause this, somehow ARRAY_IND is undefined, or somehow the order of operations is evaluating to 0 instead of 1. We can force an order of operations with some more brackets.

@josephdviviano is this error reproducible?

**Comment by josephdviviano** [comment]
Hi Gabe,

Not sure about the array job thing. A single job is submitted to the queue
and fails immediately.

The error is reproducible. I originally thought it had something to do with
the code we are trying to run, but later realised I could get around this
error by running qbatch in local mode.

Joseph's Phone

**Comment by gdevenyi** [comment]
qbatch constucts job arrays, see the header bits of "#PBS -t 1-1612"

It's one "job" with 1612 slices inside it.

Do you get 1612 errors, or one?

**Comment by josephdviviano** [comment]
Just one.

**Comment by gdevenyi** [comment]
This looks like it might be a torque bug then.

Before we go there, can you please try this stripped down command:
``qbatch -N qap-test --walltime 1:00:00 qap-cmds``

**Comment by josephdviviano** [comment]
Same thing:

`sed: -e expression #1, char 5: invalid usage of line address 0`

is all I get.

**Comment by pipitone** [comment]
The problem is that qbatch does not know it should be using SGE to submit jobs, and it defaults to using PBS/Torque. That's why PBS_ARRAYID is empty. @josephdviviano try giving qbatch `--b sge` and let us know what happens.

**Comment by pipitone** [comment]
*ahem* `-b sge`

**Comment by gdevenyi** [comment]
Hrm, should the qbatch module define that?

@josephdviviano are you using qbatch without a properly configured install?

**Comment by gdevenyi** [comment]
See https://github.com/pipitone/qbatch#environment-variable-defaults

**Comment by pipitone** [comment]
Yeah, if you look in the array job there are no `QBATCH_*` variables exported, so I suspect qbatch hasn't been properly configured.

**Comment by josephdviviano** [comment]
Ah I see. Yeah I didn't configure anything.

Might be good to have your code throw errors if qbatch been configured. This is a pretty confusing bug for an average user.

**Comment by pipitone** [comment]
@josephdviviano In the klab, SCC, and on scinet, are qbatch modules. If you load one of those before you set up your local install of qbatch, your environment will be set up correctly. In any case, I've created issue #133.

**Comment by pipitone** [comment]
@gdevenyi, since we're allowing different shells #111, how about we flip the shell to /bin/sh by default so that any bashism get caught upfront, and then close this for now?

**Comment by gdevenyi** [comment]
Merged.
